source 'https://rubygems.org'

ruby '2.5.8'

gem 'unicorn'
gem 'active_hash'
gem 'activejob-cancel'
gem 'activerecord-session_store'
gem 'acts_as_commentable'
gem 'acts_as_follower'
gem 'acts_as_votable'
#gem 'ahoy_email', '~> 1.0.2'
#gem 'ahoy_matey', '~> 2.0.2'
gem 'aws-sdk', '~> 1.0'
gem 'aws-sdk-ses'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'bootstrap-sass'
gem 'breadcrumbs_on_rails'
gem 'browser'
gem 'browserify-rails'
gem 'cancancan'
gem 'carrierwave'
gem 'chronic'
gem 'counter_culture'
gem 'daemons'
gem 'delayed_job_active_record'
gem 'devise'
gem 'era_ja'
gem 'eventmachine', '~> 1.2.0.0'
gem 'exception_notification'
gem 'fcm'
gem 'fog', '1.41.0'
gem 'font-awesome-rails', '~> 4.7.0.4'
gem 'friendly_id'
gem 'google-cloud-bigquery'
gem 'holiday_jp'
gem 'impressionist'
gem 'jbuilder', '~> 2.5'
gem 'jc-validates_timeliness'
gem 'jquery-rails'
gem 'kaminari'
gem 'mailboxer'
gem 'mini_magick'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'paper_trail'
gem 'paranoia'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.2.1'
gem 'rails_autolink'
gem 'ransack'
gem 'react-rails'
gem 'remotipart'
gem 'rest-client'
gem 'retina_tag'
gem 'rolify'
gem 'roo'
gem 'rubyXL'
gem 'rubyzip'
gem 'sass-rails', '~> 5.0'
gem 'seed-fu'
gem 'sendgrid-ruby'
gem 'serviceworker-rails'
gem 'settingslogic'
gem 'simple_form'
gem 'slack-notifier'
gem 'summernote-rails', '~> 0.8.1.0'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary', '0.12.3.1'
gem 'wkhtmltopdf-binary-edge', '0.12.4.0'
gem 'momentjs-rails'
gem 'fullcalendar-rails'
gem 'whenever', require: false

group :test do
  gem 'capybara'
  gem 'capybara-email'
  gem 'chromedriver-helper'
  gem 'database_rewinder', '~> 0.8.3'
  gem 'email_spec'
  gem 'rspec-rails', '~> 3.7.2'
  gem 'rspec-retry'
  gem 'selenium-webdriver'
  gem 'simplecov'
  gem 'simplecov-rcov'
end

group :test, :development do
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'byebug'
  gem 'sucker_punch'
  gem 'factory_bot_rails', '4.10.0'
  gem 'shoulda-matchers'
end

group :development do
  gem 'bullet'
  gem 'guard-livereload', require: false
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console'
end

group :development, :staging do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-npm'
  gem 'capistrano-passenger'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano3-delayed-job', '~> 1.0'
  gem 'derailed_benchmarks'
  gem 'elbas'
end

group :staging, :production do
  gem 'redis'
  gem 'newrelic_rpm'
end
